# Generated by Django 4.2.4 on 2023-08-30 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_tasks', '0002_task_date_created_task_date_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
